#!/bin/bash

PROJECT=ush
BRANCH=master

rm -rf export
mkdir -p export/include/ush
cp *.h export/include/ush

tar czf ${PROJECT}-${BRANCH}.tgz --directory export/ .
mv ${PROJECT}-${BRANCH}.tgz export/

