#!/bin/bash

PROJECT=ush
DESCRIBE=$(git describe)

rm -rf export
mkdir -p export/include/ush
cp *.h export/include/ush

tar czf ${PROJECT}-${DESCRIBE}.tgz --directory export/ .
mv ${PROJECT}-${DESCRIBE}.tgz export/

